### ISSUE TITLE
RewardsPanel rendering issue

### ISSUE THREAD

**Issue by aerxleben** [aerxleben/JavaAir#2]
For some reason sometimes when the rewards panel is drawn on the account welcome pannel, the JSlider shows a duplicate image of the menu bar behind it.  If you then click on "Personal Info" and then back on "Rewards" the issue is gone.  Any idea, @hitechtrex ?

**Comment by hitechtrex** [comment]
@aerxleben  in RewardsPanel.java, seems like this.setBackground() causes this strange rendering issue. Issue does not appear after that method call is disabled. Same issue with the FlightSearchPanel on the homepage.
